### ISSUE TITLE
Build IOS linphone/linphonecore.h'file not found

### ISSUE THREAD

**Issue by bigvc** [sezerkorkmaz/cordova-plugin-sip#5]
Hi. I did everything according to the instructions, but I get an error when building linphone/linphonecore.h'file not found.

**Comment by okinglee** [comment]
Me too.

**Comment by Entrecampos** [comment]
@okinglee @bigvc Did you solve it? I was thinking in installing or try another ...

**Comment by koeqatel** [comment]
For anyone who has this issue, I have had the same issue.

I fixed it by re-reading the readme, especially the part about the bridging header file.
You need to include those three lines in the bridging header file, otherwise the program cant find those files.

**Comment by sezerkorkmaz** [comment]
You must import these files in the Bridging Header File
    #include "Plugins/cordova-plugin-sip/include/linphone/lpconfig.h"
    #include "Plugins/cordova-plugin-sip/include/linphone/linphonecore.h"
    #include "Plugins/cordova-plugin-sip/include/linphone/linphonecore_utils.h"
